steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - >-
        asia-south1-docker.pkg.dev/server-side-tagging-392006/update-job/new-update-job:latest
      - ./delete_module
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - >-
        asia-south1-docker.pkg.dev/server-side-tagging-392006/update-job/new-update-job:latest
  - name: gcr.io/cloud-builders/gcloud
    args:
      - run
      - deploy
      - update-server-side
      - '--image'
      - >-
        asia-south1-docker.pkg.dev/server-side-tagging-392006/update-job/new-update-job:latest
      - '--region'
      - asia-south1
      - '--platform'
      - managed