steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - >-
        asia-south1-docker.pkg.dev/server-side-tagging-392006/dev-backend-sst/dev-backend-sst:latest
      - ./
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - >-
        asia-south1-docker.pkg.dev/server-side-tagging-392006/dev-backend-sst/dev-backend-sst:latest
  - name: gcr.io/cloud-builders/gcloud
    args:
      - run
      - deploy
      - dev-backend-sst
      - '--image'
      - >-
        asia-south1-docker.pkg.dev/server-side-tagging-392006/dev-backend-sst/dev-backend-sst:latest
      - '--region'
      - asia-south1
      - '--platform'
      - managed